controller_list:
  - name: yumi_left_controller
    action_ns: follow_left_joint_trajectory
    type: interpolate
    joints:
      - yumi_joint_1_l
      - yumi_joint_2_l
      - yumi_joint_7_l
      - yumi_joint_3_l
      - yumi_joint_4_l
      - yumi_joint_5_l
      - yumi_joint_6_l
      - gripper_l_joint
  - name: yumi_right_controller
    action_ns: follow_right_joint_trajectory
    type: interpolate
    joints:
      - yumi_joint_1_r
      - yumi_joint_2_r
      - yumi_joint_7_r
      - yumi_joint_3_r
      - yumi_joint_4_r
      - yumi_joint_5_r
      - yumi_joint_6_r
      - gripper_r_joint
  # - name: fake_left_gripper_controller
  #   joints:
  #     - gripper_l_joint
  # - name: fake_right_gripper_controller
  #   joints:
  #     - gripper_r_joint
initial:
  - group: left_arm
    pose: left_bin_home_pose
  - group: right_arm
    pose: right_bin_home_pose    